### ISSUE TITLE
incomplete context specification?

### ISSUE THREAD

**Issue by chicco785** [smart-data-models/dataModel.Streetlighting#10]
is there are any reason why data types are not defined, e.g.:

https://github.com/smart-data-models/dataModel.Streetlighting/blob/57d49f0afcc30d05ca685c716e29f560b19c148c/context.jsonld#L30

shouldn't be defined some where as of type `"@type": "DateTime"`?

**Comment by albertoabellagarcia** [comment]
They are already defined in the json schema (@type is mapped to type). Send me a mail at info@smartdatamodels with the use case, for including additionally in the @context. If approved we would change it for all of them

**Comment by chicco785** [comment]
> They are already defined in the json schema (@type is mapped to type). Send me a mail at info@smartdatamodels with the use case, for including additionally in the @context. If approved we would change it for all of them

thanks @albertoabellagarcia, for the community benefit I will explain here the rational for the request (and email you, of course).

we are now exploring the support for `ngsi-ld` context compression and expansion in [quantumleap](https://quantumleap.readthedocs.io/en/latest/). Being QL written in python, we explored json-ld libraries available, and the only one supporting expansion and compression is [pyld](https://github.com/digitalbazaar/pyld). Testing against different ngsi-ld examples. The tests aims at ensuring that expansion and compression are idempotent. 

i.e.:
```
compress(expand(compressed_message)) = compressed_message
expand(compress(expanded_message)) = expanded_message
```

now, in this second case, this is what happens, `dateLastLampChange` is compressed again as:
```
'dateLastLampChange': {
    'type': 'Property',
    'value': {
        '@value': '2016-07-08T08:02:21.753Z',
        'type': 'DateTime'
     }
},
```
while, if compression and expansion are idempotent `type` inside `value` attribute should be `@type`.
I first thought this was a bug in the library, but the observing this was not the case for `observedAt`, i checked the definition in the context, and found out that compared to `observedAt`, the typing was not defined in the context. I am not sure though, this information should be extracted from the json schema according to json-ld best practises. (I would assume no, but I am not the expert on the matter).

**Comment by albertoabellagarcia** [comment]
ok, I got your point but let me analyze the implications

**Comment by chicco785** [comment]
> ok, I got your point but let me analyze the implications

sure :) 

actually, 
```
compress(expand(compressed_message)) = compressed_message
expand(compress(expanded_message)) = expanded_message
```

could be part of the performed ci validation. at the time jose was managing the activity, i actually developed a validator based on json schemas, but I am not sure what's the ci process now, and what's the programming language used for that, but if there is a suitable library, we may help.

**Comment by albertoabellagarcia** [comment]
Could you provide further data about your use case? specifically 
1) what @context are you using in 
2) Link to the precise full payload you are testing for validation? 
3) What subscription payload are you receiving? 
Maybe we could talk on the January 10th (14:00) during the open session https://bit.ly/smartdatamodels.

**Comment by chicco785** [comment]
@albertoabellagarcia what if i provide you with a python snippet code? would that make sense and help you?

sure, let's meet on the 10th!

**Comment by albertoabellagarcia** [comment]
yes please.

**Comment by albertoabellagarcia** [comment]
Running a survey for the contributors to adopt a change in the @context. It will take a while.

**Comment by albertoabellagarcia** [comment]
There have not been any claims against it. So it will implemented.

**Comment by kzangeli** [comment]
The problem with defining an @type for items in the contexts is that we use the Normalized Representation, e.g.:
```
"aTimestamp": {
  "type": "Property",
  "value": "2022-02-18T03:44:00.000Z"
}
```
Now, if I fix "aTimestamp" to be a DateTime in my @context ("type coercion"), by adding this:
```
"aTimestamp": {
  "@id": "<longname for aTimestamp>",
  "@type": "DateTime"
}
```
to my context, then a broker receiving a request with an attribute named "aTimestamp" will respond with an error.

It's a pity, this is a powerful aspect of JSON-LD, we just can't use it for NGSI-LD.

"aTimestamp", like all other attributes has a JSON Object as RHS (in normalized form).
But, the type coercion tells the broker "aTimestamp" needs to have an RHS that is a JSON String, with a valid ISO8601.

Type coercion can only work with key-values, and while that is supported (for GET operations), we also support the Normalized format, which is currently the only accepted format for input

_[ We're working on defining a simplified input format in ETSI ISG CIM. Orion-LD actually has it implemented and working already, but, it won't be "official" until it's part of a released ETSI NGSI-LD API specification (next release is planned for Jul-Sep 2022).]_

This new input format also doesn't fix the problem as even though it allows supplying attributes like this:
```
"aTimestamp": "2022-02-18T03:55:00.000Z"
```
... the normalized format must also be supported.

Thus, the type of an attribute cannot be fixed.
Sorry.

**Comment by albertoabellagarcia** [comment]
Unfortunately it is not possible to attend this change with the current version of the standard... so we have to close the issue

**Comment by chicco785** [comment]
i don't think the issue should be closed, it should stay open and be tracked w.r.t. this clear severe issue in the NGSI-LD specs that basically invalidates it's compliance with JSON-LD.

This limitations basically imply that when you compress and the expand a message based on a context, the expansion won't correspond to the original message. which means somehow that semantically it will be different, breaking the whole design principles behind JSON-LD.

You tackle it as "minor" problem, but if NGSI-LD is built on top of JSON-LD, it should not break it's design principles, and if the problem is the NGSI-LD standard, the standard should be fixed.

**Comment by kzangeli** [comment]
Well, we can't be 100% JSON-LD. If we were, there would be no API.
E.g. if you try to create an Entity and you don't supply an "id" for it, that 's an error.
NGSI-LD is as much JSON-LD as possible, it just can't be 100%

The only way to fix this current problem is to always use key-values.
That way attributes have no sub-attributes. Goodbye "observedAt", "unitCode", etc.
That's not an option, of course.

All sub-attrs could be stored in a separate, connected attribute:
```
{
  "temperature": 23,
  "temperature-info": {
    "observedAt": "2022-...",
    "unitCode": "",
    "providedBy": "urn:..."
  }
}
```
Something like that is what I would have suggested had I been in ETSI ISG CIM from the beginning.
But, that suggestion would have been shot down after 15 minutes as one of the most important points with NGSi-LD
was to be as similar to NGSIv2 as possible.   Also, it's quite ugly.

So, this is something we simply have to live with - can't use type coercion, as all attributes are JSON objects in Normalized form, and any other JSON type in Simplified form (keyValues).

**Comment by chicco785** [comment]
Probably `id` is not the best example, because if NGSI-LD requires the id, this is not breaking JSON-LD in my understanding, and in fact the expansion and compression works correctly for id. But I am not expert in both standards,
still, I have difficulties to understand why it's fine to force the mapping from `type` to `@type` for `observedAt` but not for other - let's call them user defined - time attributes such as `dateLastLampChange`.

This looks to me more an implementation limitation than something linked to the standard definition.

**Comment by kzangeli** [comment]
`observedAt` is a special sub-attribute for NGSI-LD, explained in the NGSI-LD API spec that it has to be a JSON String that is a valid ISO8601 datetime. Similar to the "id" and "type" for an Entity.

If you ask for Normalized (well, it's the default), "observedAt" will still come as "key-values".

_FYI, Orion-LD doesn't expand "id". There's no need, as it will always be expanded and compacted using the core context and there is no way to override that. I also don't expand "type", "modifiedAt", etc for entities, and also not "observedAt" for attributes, etc.
I gain some performance with this._
