### ISSUE TITLE
Request for addition of attributes

### ISSUE THREAD

**Issue by manurag1234** [smart-data-models/dataModel.Streetlighting#11]
Hi Team,

For streetlight, we need a parameter for "lifetimeMotionDetected" and "lifetimePowerConsumption" can we add "peopleCount[number]" mentioned in "CrowdFlowObserved" data model to "streetlight" datamodel for counting "lifetimeMotionDetected" ?
if not please add below 2 models:
"lifetimeMotionDetected":{
	"type": "Integer",
	"value": 10
	},
"lifetimePowerConsumption":{
	"type": "Integer",
	"value": 10
	},

**Comment by albertoabellagarcia** [comment]
interesting. Please provide the extension of the schema and the example according to the [contribution manual](https://bit.ly/contribution_manual). Find support [in this page](https://smartdatamodels.org/index.php/support/).

**Comment by albertoabellagarcia** [comment]
If you have doubts you can use this thread or you can book a support session [here](https://calendly.com/smartdatamodels)

**Comment by albertoabellagarcia** [comment]
I see your PR. Please address the comments. closing the issue. thanks
