### ISSUE TITLE
latern or lantern?

### ISSUE THREAD

**Issue by chicco785** [smart-data-models/dataModel.Streetlighting#9]
in the schema:

https://github.com/smart-data-models/dataModel.Streetlighting/blob/ecd530bb7d9ab618fbf1308afb3fde17303bbff7/context.jsonld#L64

in the example:
https://github.com/smart-data-models/dataModel.Streetlighting/blob/2a16b21600245206a046f980c64e9fa96856f065/Streetlight/examples/example.json#L16

which also means that the automated checkers didn't spot the issue...

**Comment by albertoabellagarcia** [comment]
This is a typo we have fixed now.
Thank you very much
